on:
  push:
  schedule:
    - cron: '30 2 * * 0'
name: build
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.10', '9.0', '9.2']
        os: [ubuntu-latest, macOS-latest, windows-latest]

    name: Build Package
    steps:
      - uses: actions/checkout@v2

      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Build
        run: cabal build

      - name: Test
        run: cabal test
